#pragma once
#include <stdio.h>
#include <string>
#include "srpc/rpc_define.h"
#include "auth.pb.h"

namespace pacs
{

namespace auth
{

namespace AuthService
{

/*
 * Server codes
 * Generated by SRPC
 */

class Service : public srpc::RPCService
{
public:
	// please implement these methods in server.cc

	virtual void Login(LoginRequest *request, LoginResponse *response,
					srpc::RPCContext *ctx) = 0;

	virtual void Verify(VerifyRequest *request, VerifyResponse *response,
					srpc::RPCContext *ctx) = 0;

public:
	Service();
};

/*
 * Client codes
 * Generated by SRPC
 */

using LoginDone = std::function<void (LoginResponse *, srpc::RPCContext *)>;
using VerifyDone = std::function<void (VerifyResponse *, srpc::RPCContext *)>;

class SRPCClient : public srpc::SRPCClient
{
public:
	void Login(const LoginRequest *req, LoginDone done);
	void Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> async_Login(const LoginRequest *req);

	void Verify(const VerifyRequest *req, VerifyDone done);
	void Verify(const VerifyRequest *req, VerifyResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<VerifyResponse, srpc::RPCSyncContext>> async_Verify(const VerifyRequest *req);

public:
	SRPCClient(const char *host, unsigned short port);
	SRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCClientTask *create_Login_task(LoginDone done);
	srpc::SRPCClientTask *create_Verify_task(VerifyDone done);
};

class SRPCHttpClient : public srpc::SRPCHttpClient
{
public:
	void Login(const LoginRequest *req, LoginDone done);
	void Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> async_Login(const LoginRequest *req);

	void Verify(const VerifyRequest *req, VerifyDone done);
	void Verify(const VerifyRequest *req, VerifyResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<VerifyResponse, srpc::RPCSyncContext>> async_Verify(const VerifyRequest *req);

public:
	SRPCHttpClient(const char *host, unsigned short port);
	SRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCHttpClientTask *create_Login_task(LoginDone done);
	srpc::SRPCHttpClientTask *create_Verify_task(VerifyDone done);
};

class BRPCClient : public srpc::BRPCClient
{
public:
	void Login(const LoginRequest *req, LoginDone done);
	void Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> async_Login(const LoginRequest *req);

	void Verify(const VerifyRequest *req, VerifyDone done);
	void Verify(const VerifyRequest *req, VerifyResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<VerifyResponse, srpc::RPCSyncContext>> async_Verify(const VerifyRequest *req);

public:
	BRPCClient(const char *host, unsigned short port);
	BRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::BRPCClientTask *create_Login_task(LoginDone done);
	srpc::BRPCClientTask *create_Verify_task(VerifyDone done);
};

class TRPCClient : public srpc::TRPCClient
{
public:
	void Login(const LoginRequest *req, LoginDone done);
	void Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> async_Login(const LoginRequest *req);

	void Verify(const VerifyRequest *req, VerifyDone done);
	void Verify(const VerifyRequest *req, VerifyResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<VerifyResponse, srpc::RPCSyncContext>> async_Verify(const VerifyRequest *req);

public:
	TRPCClient(const char *host, unsigned short port);
	TRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCClientTask *create_Login_task(LoginDone done);
	srpc::TRPCClientTask *create_Verify_task(VerifyDone done);
};

class TRPCHttpClient : public srpc::TRPCHttpClient
{
public:
	void Login(const LoginRequest *req, LoginDone done);
	void Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> async_Login(const LoginRequest *req);

	void Verify(const VerifyRequest *req, VerifyDone done);
	void Verify(const VerifyRequest *req, VerifyResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<VerifyResponse, srpc::RPCSyncContext>> async_Verify(const VerifyRequest *req);

public:
	TRPCHttpClient(const char *host, unsigned short port);
	TRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCHttpClientTask *create_Login_task(LoginDone done);
	srpc::TRPCHttpClientTask *create_Verify_task(VerifyDone done);
};

///// implements detials /////

inline Service::Service(): srpc::RPCService("pacs.auth.AuthService")
{
	this->srpc::RPCService::add_method("Login",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::Login);
		});

	this->srpc::RPCService::add_method("Verify",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::Verify);
		});
}

inline SRPCClient::SRPCClient(const char *host, unsigned short port):
	srpc::SRPCClient("pacs.auth.AuthService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCClient::init(&params);
}

inline SRPCClient::SRPCClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCClient("pacs.auth.AuthService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCClient::init(temp);
}

inline void SRPCClient::Login(const LoginRequest *req, LoginDone done)
{
	auto *task = this->create_rpc_client_task("Login", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Login(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> SRPCClient::async_Login(const LoginRequest *req)
{
	using RESULT = std::pair<LoginResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<LoginResponse>("Login", srpc::RPCAsyncFutureCallback<LoginResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCClient::Verify(const VerifyRequest *req, VerifyDone done)
{
	auto *task = this->create_rpc_client_task("Verify", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::Verify(const VerifyRequest *req, VerifyResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Verify(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<VerifyResponse, srpc::RPCSyncContext>> SRPCClient::async_Verify(const VerifyRequest *req)
{
	using RESULT = std::pair<VerifyResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<VerifyResponse>("Verify", srpc::RPCAsyncFutureCallback<VerifyResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCClientTask *SRPCClient::create_Login_task(LoginDone done)
{
	return this->create_rpc_client_task("Login", std::move(done));
}

inline srpc::SRPCClientTask *SRPCClient::create_Verify_task(VerifyDone done)
{
	return this->create_rpc_client_task("Verify", std::move(done));
}

inline SRPCHttpClient::SRPCHttpClient(const char *host, unsigned short port):
	srpc::SRPCHttpClient("pacs/auth/AuthService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCHttpClient::init(&params);
}

inline SRPCHttpClient::SRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCHttpClient("pacs/auth/AuthService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCHttpClient::init(temp);
}

inline void SRPCHttpClient::Login(const LoginRequest *req, LoginDone done)
{
	auto *task = this->create_rpc_client_task("Login", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Login(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> SRPCHttpClient::async_Login(const LoginRequest *req)
{
	using RESULT = std::pair<LoginResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<LoginResponse>("Login", srpc::RPCAsyncFutureCallback<LoginResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCHttpClient::Verify(const VerifyRequest *req, VerifyDone done)
{
	auto *task = this->create_rpc_client_task("Verify", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::Verify(const VerifyRequest *req, VerifyResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Verify(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<VerifyResponse, srpc::RPCSyncContext>> SRPCHttpClient::async_Verify(const VerifyRequest *req)
{
	using RESULT = std::pair<VerifyResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<VerifyResponse>("Verify", srpc::RPCAsyncFutureCallback<VerifyResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_Login_task(LoginDone done)
{
	return this->create_rpc_client_task("Login", std::move(done));
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_Verify_task(VerifyDone done)
{
	return this->create_rpc_client_task("Verify", std::move(done));
}

inline BRPCClient::BRPCClient(const char *host, unsigned short port):
	srpc::BRPCClient("pacs.auth.AuthService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::BRPCClient::init(&params);
}

inline BRPCClient::BRPCClient(const struct srpc::RPCClientParams *params):
	srpc::BRPCClient("pacs.auth.AuthService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::BRPCClient::init(temp);
}

inline void BRPCClient::Login(const LoginRequest *req, LoginDone done)
{
	auto *task = this->create_rpc_client_task("Login", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Login(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> BRPCClient::async_Login(const LoginRequest *req)
{
	using RESULT = std::pair<LoginResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<LoginResponse>("Login", srpc::RPCAsyncFutureCallback<LoginResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void BRPCClient::Verify(const VerifyRequest *req, VerifyDone done)
{
	auto *task = this->create_rpc_client_task("Verify", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::Verify(const VerifyRequest *req, VerifyResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Verify(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<VerifyResponse, srpc::RPCSyncContext>> BRPCClient::async_Verify(const VerifyRequest *req)
{
	using RESULT = std::pair<VerifyResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<VerifyResponse>("Verify", srpc::RPCAsyncFutureCallback<VerifyResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::BRPCClientTask *BRPCClient::create_Login_task(LoginDone done)
{
	return this->create_rpc_client_task("Login", std::move(done));
}

inline srpc::BRPCClientTask *BRPCClient::create_Verify_task(VerifyDone done)
{
	return this->create_rpc_client_task("Verify", std::move(done));
}

inline TRPCClient::TRPCClient(const char *host, unsigned short port):
	srpc::TRPCClient("pacs.auth.AuthService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCClient::init(&params);
}

inline TRPCClient::TRPCClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCClient("pacs.auth.AuthService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCClient::init(temp);
}

inline void TRPCClient::Login(const LoginRequest *req, LoginDone done)
{
	auto *task = this->create_rpc_client_task("/pacs.auth.AuthService/Login", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Login(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> TRPCClient::async_Login(const LoginRequest *req)
{
	using RESULT = std::pair<LoginResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<LoginResponse>("/pacs.auth.AuthService/Login", srpc::RPCAsyncFutureCallback<LoginResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCClient::Verify(const VerifyRequest *req, VerifyDone done)
{
	auto *task = this->create_rpc_client_task("/pacs.auth.AuthService/Verify", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::Verify(const VerifyRequest *req, VerifyResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Verify(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<VerifyResponse, srpc::RPCSyncContext>> TRPCClient::async_Verify(const VerifyRequest *req)
{
	using RESULT = std::pair<VerifyResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<VerifyResponse>("/pacs.auth.AuthService/Verify", srpc::RPCAsyncFutureCallback<VerifyResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCClientTask *TRPCClient::create_Login_task(LoginDone done)
{
	auto *task = this->create_rpc_client_task("/pacs.auth.AuthService/Login", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCClientTask *TRPCClient::create_Verify_task(VerifyDone done)
{
	auto *task = this->create_rpc_client_task("/pacs.auth.AuthService/Verify", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline TRPCHttpClient::TRPCHttpClient(const char *host, unsigned short port):
	srpc::TRPCHttpClient("pacs.auth.AuthService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCHttpClient::init(&params);
}

inline TRPCHttpClient::TRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCHttpClient("pacs.auth.AuthService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCHttpClient::init(temp);
}

inline void TRPCHttpClient::Login(const LoginRequest *req, LoginDone done)
{
	auto *task = this->create_rpc_client_task("Login", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::Login(const LoginRequest *req, LoginResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Login(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<LoginResponse, srpc::RPCSyncContext>> TRPCHttpClient::async_Login(const LoginRequest *req)
{
	using RESULT = std::pair<LoginResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<LoginResponse>("Login", srpc::RPCAsyncFutureCallback<LoginResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCHttpClient::Verify(const VerifyRequest *req, VerifyDone done)
{
	auto *task = this->create_rpc_client_task("Verify", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::Verify(const VerifyRequest *req, VerifyResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Verify(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<VerifyResponse, srpc::RPCSyncContext>> TRPCHttpClient::async_Verify(const VerifyRequest *req)
{
	using RESULT = std::pair<VerifyResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<VerifyResponse>("Verify", srpc::RPCAsyncFutureCallback<VerifyResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_Login_task(LoginDone done)
{
	auto *task = this->create_rpc_client_task("Login", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_Verify_task(VerifyDone done)
{
	auto *task = this->create_rpc_client_task("Verify", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

} // end namespace AuthService

} // end namespace auth

} // end namespace pacs

